<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="9" total="11" passed="0" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-09-11T13:42:08 PKT" name="Default suite" finished-at="2025-09-11T13:43:06 PKT" duration-ms="57931">
    <groups>
      <group name="negative">
        <method signature="LoginTests.NegativeTest_LoginWithWrongCredential(java.util.Map)[pri:0, instance:com.automation.tests.LoginTests@f001896]" name="NegativeTest_LoginWithWrongCredential" class="com.automation.tests.LoginTests"/>
      </group> <!-- negative -->
      <group name="login">
        <method signature="LoginTests.NegativeTest_LoginWithWrongCredential(java.util.Map)[pri:0, instance:com.automation.tests.LoginTests@f001896]" name="NegativeTest_LoginWithWrongCredential" class="com.automation.tests.LoginTests"/>
      </group> <!-- login -->
    </groups>
    <test started-at="2025-09-11T13:42:08 PKT" name="Default test" finished-at="2025-09-11T13:43:06 PKT" duration-ms="57931">
      <class name="com.automation.tests.LoginTests">
        <test-method is-config="true" signature="setupSuite()[pri:0, instance:com.automation.tests.LoginTests@f001896]" started-at="2025-09-11T13:42:08 PKT" name="setupSuite" finished-at="2025-09-11T13:42:08 PKT" duration-ms="229" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupSuite -->
        <test-method is-config="true" signature="setupTest(java.lang.reflect.Method)[pri:0, instance:com.automation.tests.LoginTests@f001896]" started-at="2025-09-11T13:42:08 PKT" name="setupTest" finished-at="2025-09-11T13:42:13 PKT" duration-ms="5280" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.automation.tests.LoginTests.NegativeTest_LoginWithWrongCredential(java.util.Map)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupTest -->
        <test-method is-config="true" signature="initPage()[pri:0, instance:com.automation.tests.LoginTests@f001896]" started-at="2025-09-11T13:42:13 PKT" name="initPage" finished-at="2025-09-11T13:42:13 PKT" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initPage -->
        <test-method signature="NegativeTest_LoginWithWrongCredential(java.util.Map)[pri:0, instance:com.automation.tests.LoginTests@f001896]" started-at="2025-09-11T13:42:13 PKT" name="NegativeTest_LoginWithWrongCredential" data-provider="InvalidCredentials" finished-at="2025-09-11T13:42:36 PKT" duration-ms="22887" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=qtestor@yopmail.com, phone=, password=WrongPass1!, assert=Incorrect password!}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected text to contain: 'Incorrect password!', but got: 'null']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected text to contain: 'Incorrect password!', but got: 'null'
at com.automation.utils.AssertUtils.assertContains(AssertUtils.java:36)
at com.automation.tests.LoginTests.NegativeTest_LoginWithWrongCredential(LoginTests.java:225)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NegativeTest_LoginWithWrongCredential -->
        <test-method is-config="true" signature="tearDownTest(org.testng.ITestResult)[pri:0, instance:com.automation.tests.LoginTests@f001896]" started-at="2025-09-11T13:42:36 PKT" name="tearDownTest" finished-at="2025-09-11T13:42:39 PKT" duration-ms="2330" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=NegativeTest_LoginWithWrongCredential status=FAILURE method=LoginTests.NegativeTest_LoginWithWrongCredential(java.util.Map)[pri:0, instance:com.automation.tests.LoginTests@f001896] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownTest -->
        <test-method is-config="true" signature="setupTest(java.lang.reflect.Method)[pri:0, instance:com.automation.tests.LoginTests@f001896]" started-at="2025-09-11T13:42:39 PKT" name="setupTest" finished-at="2025-09-11T13:42:42 PKT" duration-ms="3106" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.automation.tests.LoginTests.NegativeTest_LoginWithWrongCredential(java.util.Map)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupTest -->
        <test-method is-config="true" signature="initPage()[pri:0, instance:com.automation.tests.LoginTests@f001896]" started-at="2025-09-11T13:42:42 PKT" name="initPage" finished-at="2025-09-11T13:42:42 PKT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initPage -->
        <test-method signature="NegativeTest_LoginWithWrongCredential(java.util.Map)[pri:0, instance:com.automation.tests.LoginTests@f001896]" started-at="2025-09-11T13:42:42 PKT" name="NegativeTest_LoginWithWrongCredential" data-provider="InvalidCredentials" finished-at="2025-09-11T13:43:04 PKT" duration-ms="22353" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=, phone=7856125645, password=Xyz@4312, assert=User not found!}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected text to contain: 'User not found!', but got: 'null']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected text to contain: 'User not found!', but got: 'null'
at com.automation.utils.AssertUtils.assertContains(AssertUtils.java:36)
at com.automation.tests.LoginTests.NegativeTest_LoginWithWrongCredential(LoginTests.java:225)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NegativeTest_LoginWithWrongCredential -->
        <test-method is-config="true" signature="tearDownTest(org.testng.ITestResult)[pri:0, instance:com.automation.tests.LoginTests@f001896]" started-at="2025-09-11T13:43:04 PKT" name="tearDownTest" finished-at="2025-09-11T13:43:06 PKT" duration-ms="1907" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=NegativeTest_LoginWithWrongCredential status=FAILURE method=LoginTests.NegativeTest_LoginWithWrongCredential(java.util.Map)[pri:0, instance:com.automation.tests.LoginTests@f001896] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownTest -->
        <test-method is-config="true" signature="tearDownSuite()[pri:0, instance:com.automation.tests.LoginTests@f001896]" started-at="2025-09-11T13:43:06 PKT" name="tearDownSuite" finished-at="2025-09-11T13:43:06 PKT" duration-ms="16" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownSuite -->
      </class> <!-- com.automation.tests.LoginTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
